//Create Custom Presets for ACRE2 Radios
["ACRE_PRC117F", "default", "mission1"] call acre_api_fnc_copyPreset;
["ACRE_PRC152", "default1", "mission2"] call acre_api_fnc_copyPreset;

//PRC 117F Presets
["ACRE_PRC117F", "mission1", 1,  "name", "COYNET 1"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC117F", "mission1", 2,  "name", "COYNET 2"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC117F", "mission1", 3,  "name", "PLTNET 1"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC117F", "mission1", 4,  "name", "PLTNET 2"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC117F", "mission1", 5,  "name", "PLTNET 3"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC117F", "mission1", 6,  "name", "PLTNET 4"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC117F", "mission1", 7,  "name", "PLTNET 5"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC117F", "mission1", 8,  "name", "PLTNET 6"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC117F", "mission1", 9,  "name", "PLTNET 7"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC117F", "mission1", 10, "name", "PLTNET 8"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC117F", "mission1", 11, "name", "CAS"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC117F", "mission1", 12, "name", "FIRES"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC117F", "mission1", 13, "name", "MEDEVAC"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC117F", "mission1", 14, "name", "LOGISTIC"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC117F", "mission1", 15, "name", "BACKUP 1"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC117F", "mission1", 16, "name", "BACKUP 2"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC117F", "mission1", 17, "name", "BACKUP 3"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC117F", "mission1", 18, "name", "BACKUP 4"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC117F", "mission1", 19, "name", "BACKUP 5"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC117F", "mission1", 20, "name", "ZEUS"] call acre_api_fnc_setPresetChannelField;

//PRC 152 Presets
["ACRE_PRC152", "mission2", 1,  "description", "SQNET 1"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 2,  "description", "SQNET 2"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 3,  "description", "SQNET 3"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 4,  "description", "SQNET 4"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 5,  "description", "SQNET 5"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 6,  "description", "SQNET 6"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 7,  "description", "SQNET 7"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 8,  "description", "SQNET 8"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 9,  "description", "SQNET 9"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 10, "description", "SQNET 10"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 11, "description", "SQNET 11"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 12, "description", "SQNET 12"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 13, "description", "SQNET 13"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 14, "description", "SQNET 14"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 15, "description", "SQNET 15"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 16, "description", "SQNET 16"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 17, "description", "SQNET 17"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 18, "description", "SQNET 18"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 19, "description", "SQNET 19"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 20, "description", "SQNET 20"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 21, "description", "SQNET 21"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 22, "description", "SQNET 22"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 23, "description", "SQNET 23"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 24, "description", "SQNET 24"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 25, "description", "SQNET 25"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 26, "description", "SQNET 26"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 27, "description", "SQNET 27"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 28, "description", "SQNET 28"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 29, "description", "SQNET 29"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 30, "description", "SQNET 30"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 31, "description", "SQNET 31"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 32, "description", "SQNET 32"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 33, "description", "BACKUP 1"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 34, "description", "BACKUP 2"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 35, "description", "BACKUP 3"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 36, "description", "BACKUP 4"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 37, "description", "BACKUP 5"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 38, "description", "BACKUP 6"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 39, "description", "BACKUP 7"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 40, "description", "BACKUP 8"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 41, "description", "COYNET 1"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 42, "description", "COYNET 2"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 43, "description", "PLTNET 1"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 44, "description", "PLTNET 2"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 45, "description", "PLTNET 3"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 46, "description", "PLTNET 4"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 47, "description", "PLTNET 5"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 48, "description", "PLTNET 6"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 49, "description", "PLTNET 7"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 50, "description", "PLTNET 8"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 51, "description", "CAS"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 52, "description", "FIRES"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 53, "description", "MEDEVAC"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 54, "description", "LOGISTIC"] call acre_api_fnc_setPresetChannelField;
["ACRE_PRC152", "mission2", 55, "description", "ZEUS"] call acre_api_fnc_setPresetChannelField;

//Set Preset on Radio
["ACRE_PRC117F", "mission1"] call acre_api_fnc_setPreset;
["ACRE_PRC152", "mission1"] call acre_api_fnc_setPreset;